### ISSUE TITLE
roll problem

### ISSUE THREAD

**Issue by aortner** [AgOpenGPS-Official/AgOpenGPS#31]
i did report thats a problem to drive with contour or a-b curve.

so i did look what is might going wrong. i think i found the problem at working with
roll.
my setup dual antenna, 83 cm offset, roll from vektor (avr - working with paogi)
i did take a street with 4 degrees of roll and did drive on a straight line by hand.
i did turned roll to off. i drove one direction did turn and did drive back.
the result you can see here:

![img_3258 medium](https://user-images.githubusercontent.com/23136635/38926436-f33b28ec-4302-11e8-90e6-f00a32a56335.JPG)

so you can see offset and my driving seems to be ok. because i am drive back with same line everything is 100 % the same

after that i did setup roll and restart agopen gps.
the result was this:
![img_3259 medium](https://user-images.githubusercontent.com/23136635/38926512-3e8c8aca-4303-11e8-8983-dceefab605a2.JPG)
i thought mybe the roll is viceversa so i did change it in receiver settings: +-
the result was the same:
![img_3260 medium](https://user-images.githubusercontent.com/23136635/38926544-57f67016-4303-11e8-8edd-adbfcc63e487.JPG)

**Comment by aortner** [comment]
did add some code to simulate: i see that tractor is only moving to the right - no to the left...


   //roll 10
            if (keyData == Keys.Q)
            {
              mc.rollRaw = mc.rollRaw + 16;
                return true;
            }
            //roll -10
            if (keyData == Keys.W)
            {
              mc.rollRaw = mc.rollRaw - 16;
             
                return true;
            }

            //roll 0
            if (keyData == Keys.E)
            {
                mc.rollRaw = 0;
                return true;
            }

**Comment by farmerbriantee** [comment]
I going to have to use the old code again.

**Comment by aortner** [comment]
https://www.youtube.com/watch?v=HAOHaSdBqYk

**Comment by aortner** [comment]
i see that : rollCorrectionDistance is allways positve..

**Comment by aortner** [comment]
![image](https://user-images.githubusercontent.com/23136635/38951132-eaaddd88-4347-11e8-8542-d1393210f380.png)

calculations seems to be ok. 10 degrees with 3 m = 52,9 cm
