### ISSUE TITLE
The boundary with AB lines

### ISSUE THREAD

**Issue by lazicsasalaki** [AgOpenGPS-Official/AgOpenGPS#418]
Is it possible and how to create a boundary with AB lines in KML format?

**Comment by Davidwedel** [comment]
Are you asking:
1. If it's possible to create a field with boundary and AB Lines in AOG and then export them as KML
2. If it's possible to create a boundary *from* AB Lines
3. Import a boundary and AB Lines into AOG from KML

Also, the "Issues" in GitHub are for discussing issues or bugs in the program or code. General discussion happens at https://discourse.agopengps.com

**Comment by gunicsba** [comment]
You can import KML and create boundary from it.
You can generate boundary curve.

**Comment by steran82** [comment]
@lazicsasalaki can you close the issue because it's not really an issue. :-)
